### ISSUE TITLE
Express.js options not being passed to middleware

### ISSUE THREAD

**Issue by XhmikosR** [errorception/staticify#12]
So, it seems that currently only these are being passed to `send`:

```js
maxage: filePath === req.url ? 0 : MAX_AGE,
index: options.index || 'index.html',
ignore: options.hidden,
```

Now, I wonder, can't we inherit the options from static-serve or something?

Supporting individually our own options seems cumbersome and a lot of duplication.

**Comment by rakeshpai** [comment]
Doesn't look like static-serve is doing much more. https://github.com/PrototypeInteractive/static-serve/blob/bee33e56b9217b29a37dc05b6d803855645102d0/config/express.js Copying stuff from there isn't the hugest duplication concern, if you ask me. I'm not sure how we can inherit options from there. IIRC, `send` already ships with sensible defaults.

Alternatively, we could consider passing all unknown options to `send`, so that users of this module can configure `send` if they want to. Should be fairly easy to do with ES6 object destructuring, and rest/spread-ing that with our defaults.

**Comment by XhmikosR** [comment]
Sorry, I meant [serve-static](https://github.com/expressjs/serve-static) :/

It's just that

1. I'm not sure how performant is `send`? On the other hand, it seems serve-static is using `send` too
2. I for one would like to be able to set `immutable`, `etag` etc.

I don't mind duplication, but I'm not familiar with handling options. If you could help me with the `shortHash` branch, and do any refactoring needed, I could pick up things from there :)

**Comment by rakeshpai** [comment]
```
module.exports = (root, options = {}) => {
```
can change to
```
module.exports = (root, {
  shortHash = true,
  hidden = true,
  ...sendOptions
} = {}) => {
```
You can later use `shortHash` and other properties directly (instead of `options.shortHash`). When calling send, you can do the following:
```
return send(req, filePath, {
  maxage: filePath === req.url ? 0 : MAX_AGE,
  index: 'index.html',
  ignore: hidden,
  root,
  ...sendOptions
});
 ```

I haven't actually tried the code above, so there might be errors. But that should give you an idea of what I mean. Basically, I'm using ES6 default parameters to extract properties that I care about (`sendHash`, `hidden`, etc), and holding the remaining properties in `sendOptions`. Later, I pass my default params to `send`, and spread `sendOptions` over it, letting it override my defaults. This way, we've succinctly specified defaults, and let the user override it externally.

HTH.

**Comment by rakeshpai** [comment]
Must add - the downside with the approach above is that it uses shiny new ES6 features, so it might restrict the node versions that this module can run on. Which is fine, honestly. Let's just signal that correctly in our package.json. I'm not sure which version of node got these features, though.

**Comment by XhmikosR** [comment]
I can't make it work from a quick look; the `shortHashes` is always true.

Anyway, we need to refactor it so that the options are inherited in all functions and not the way I have it now, where I pass it as an extra parameter in most functions.

**Comment by rakeshpai** [comment]
Cool. Getting late in the night here, but I'll give the refactoring a stab tomorrow.

**Comment by rakeshpai** [comment]
Added a commit to the branch. Diff here: https://github.com/errorception/staticify/commit/ff47227c8f28c72c0842853c153b42a77de2e43a All tests pass.

Diff should be self-explanatory. I've stripped out the passing of `sendHash` as arguments to functions, since (a) it's available everywhere already due to closure scope, and (b) it already has a default value set.

What's probably not clear is that now we can `require('staticify')(..., { hidden: true, foo: 'bar' })`. When we're calling send, we pass it the additional `foo: 'bar'` property which we don't handle. This is handled by `sendOptions`.

Hope that made sense. Feel free to ask if anything's unclear. Also, worth bringing up again - I'm not sure which version of node supports this syntax. (Locally I'm on 8.x.) We'll need to specifiy this in the `engines` field in package.json.

**Comment by rakeshpai** [comment]
While we're at it, we can drop the `index` and `ignore` properties. `index` already has a good default in `send`, and I don't know what I was thinking with `ignore` - it isn't a property that send supports.

**Comment by rakeshpai** [comment]
https://github.com/errorception/staticify/commit/1a40f9d669f87cd6bb1dd0eae0e8d6ed8c9ced5a I've dropped the index and hidden properties, and made some cosmetic changes (mostly using arrow functions).

Also, it looks like a lot of work to support both short and long hashes. We could simply drop support for long hashes and stick with short hashes. I don't think anyone will miss the long hashes. ;)

**Comment by rakeshpai** [comment]
[Travis says](https://travis-ci.org/errorception/staticify/builds/318428288) that this syntax is node 8.x+ only.

**Comment by XhmikosR** [comment]
A couple of thoughts.

I had another way on mind, which I actually tried it locally yesterday but dropped due to lack of time.

1. We should use `module.exports` at the top of the file and specify what we export
2. A more OOP design, maybe with just plain `prototype` and constructor; that way the objects should be available in all functions. What I couldn't make work was the default options and moving `buildVersionHash` somewhere so that it can access the options object

**Comment by rakeshpai** [comment]
I don't think this is necessarily a good idea. I personally keep away from OO programming in JS. The extra faffing about with prototypes, `this`, `bind`, etc. doesn't provide much in terms of functionality or clarity, if you ask me. On the contrary, I think it's actively confusing. It does provide a minor optimisation (if that) because of a shared prototype. However, you only benefit from it if you are creating multiple instances, which doesn't apply here. I prefer stuff being in just bare functions, and using lexical/closure scope for private state. OO is ultimately about encapsulating state after all, and JS provides closures to do that.

I like to think of OO in JS as being really bad training wheels. It's training wheels because it's what newcomers look for, with their experience from other languages. However, once they understand how different it is from OO in other languages, and that everything it offers can be done with functions instead, it's probably best to abandon OO altogether and use functions and lexical scope instead.

About module.exports being at the top - this could be mostly a stylistic choice. I prefer it to be at the bottom. My reasoning is that when you use something, it should be defined first. (In fact, I noticed that the linter you added enforces this rule.) (Also, I don't like relying on JS's hoisting rules, which need an understanding of edge-cases.) So all the small 'unit' stuff happens at the top, and the big wrapper stuff that's exported happens at the bottom. In this module's case, the actual functions that the user uses are returned from the initializer function, so I think it's natural for it to be at the bottom of the function, like any return value. I personally don't think there's anything to be gained by moving it up.

**Comment by XhmikosR** [comment]
Top - bottom, I don't mind. I just wanted to point out we should have the main export indented. :)

Regarding OOP. I don't mind either, as long as we find a good way to share the options across the whole file, thus without the need to pass an extra option to `buildVersionHash` and without duplicating the `slice` call when `shortHash` is `false`.
