### ISSUE TITLE
Add support for TypeScript definitions

### ISSUE THREAD

**Issue by andrewsantarin** [errorception/staticify#48]
Tried this module. Works great. But it's a bit doesn't have types built into it, so when I attempt to use it in a TypeScript project, the compiler complains. I've been looking for this in DefinitelyTyped.org but found nothing.

I've prepped a gist here:
https://gist.github.com/andrewsantarin/1aa57d63049798c33b22619c064afa07

**Comment by rakeshpai** [comment]
Hi @andrewsantarin. This looks awesome. Could you create a PR for this, with the required changes to `package.json` to reference this `.d.ts` file? Also, it would be great if you could maintain the typings at least in the short time while we iron out any immediate issues with the types. But otherwise, this seems totally legit to add to the repo. 👍

**Comment by andrewsantarin** [comment]
Will do, will do. 👌

**Comment by andrewsantarin** [comment]
@rakeshpai done; see pull request #49
